### ISSUE TITLE
Filesystem plugin fails when missing command(s)

### ISSUE THREAD

**Issue by ant1441** [chef/ohai#1011]
## Description

When running Ohai on a minimal system lacking the required commands used by the 'filesystem' plugin, no output is produced.
  
For example, (on linux) if the `mount` command is missing, the `shell_out` function will fail at [filesystem.rb#L133](https://github.com/chef/ohai/blob/03a9cf30487f4ef281fb46a7e5c266fd778a0f93/lib/ohai/plugins/linux/filesystem.rb#L133), resulting in the `ohai filesystem` command giving an error like 

    /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/system.rb:211:in `attributes_print': I cannot find an attribute named filesystem! (ArgumentError)

I believe that Ohai can still give valuable information collected by the other available commands if some are not available. For example if I alias `mount` and `blkid` to `true` in the centos:6 Docker container I still get useful output via the `df` commands.
If not, it may be valuable to report the lack of suitable commands to the user, to allow simpler resolution without requiring the Ohai debug output.

I originally encountered this issue running a Kitchen test suite under the dokken provisioner, where the `node["filesystem"]` attribute is missing due to this issue.

The following sequence of commands are suitable to reproduce this issue:

```
docker run -it centos:6 /bin/bash
command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
curl -L get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm install ruby
gem install ohai
ohai filesystem -l debug
```

## Ohai Version

    [root@89d17baf2cea /]# ohai --version
    Ohai: 13.1.0

## Platform Version

cento6 (Specifically, the centos:6 Docker image - with image id 27f7cebb4137)

## Ohai Output

```
[root@89d17baf2cea /]# ohai filesystem -l debug
[2017-06-07T15:19:13+00:00] DEBUG: Running Ohai with the following configuration: {:log_location=>#<IO:<STDERR>>, :log_level=>:debug, :invoked_from_cli=>true}
[2017-06-07T15:19:13+00:00] DEBUG: Searching for Ohai plugins in /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/plugins
[2017-06-07T15:19:13+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
[2017-06-07T15:19:13+00:00] DEBUG: Loading plugin at /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/plugins/root_group.rb
... <loading further plugins>
[2017-06-07T15:19:13+00:00] DEBUG: Plugin Filesystem: ran 'df -P' and returned 0
[2017-06-07T15:19:13+00:00] DEBUG: Plugin Filesystem: ran 'df -iP' and returned 0
[2017-06-07T15:19:13+00:00] DEBUG: Plugin Filesystem: ran 'mount' and failed #<Errno::ENOENT: No such file or directory - mount>
[2017-06-07T15:19:13+00:00] DEBUG: Plugin Filesystem threw #<Ohai::Exceptions::Exec: No such file or directory - mount>
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/mixin/command.rb:44:in `rescue in shell_out'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/mixin/command.rb:38:in `shell_out'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/plugins/linux/filesystem.rb:133:in `block (2 levels) in <main>'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/dsl/plugin/versionvii.rb:88:in `instance_eval'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/dsl/plugin/versionvii.rb:88:in `run_plugin'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/dsl/plugin.rb:100:in `run'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/dsl/plugin.rb:184:in `safe_run'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/runner.rb:84:in `run_v7_plugin'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/runner.rb:43:in `run_plugin'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/system.rb:104:in `block in run_plugins'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/system.rb:103:in `each'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/system.rb:103:in `run_plugins'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/system.rb:81:in `all_plugins'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/application.rb:93:in `run_application'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/application.rb:78:in `run'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/bin/ohai:41:in `<top (required)>'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/bin/ohai:23:in `load'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/bin/ohai:23:in `<main>'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
[2017-06-07T15:19:13+00:00] DEBUG: /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
/usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/system.rb:211:in `attributes_print': I cannot find an attribute named filesystem! (ArgumentError)
	from /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/application.rb:97:in `block in run_application'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/application.rb:96:in `each'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/application.rb:96:in `run_application'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/lib/ohai/application.rb:78:in `run'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/ohai-13.1.0/bin/ohai:41:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/ohai:23:in `load'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/ohai:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by tas50** [comment]
We just merged some fixes to filesystem that make it a bit more resilient, but if you want to add some error handling in a PR I'd gladly accept that. You're right that we shouldn't bail on a single failure. We should keep trying to get any information we can.

**Comment by jeunito** [comment]
> if you want to add some error handling in a PR I'd gladly accept that

@tas50 I made a PR for this

**Comment by tas50** [comment]
This has been fixed on master and will ship in the next Ohai/Chef release. Thanks @jeunito for tackling it

**Comment by jeunito** [comment]
@ant1441 please beware that this isn't the default behavior anymore but is still available https://github.com/chef/ohai/pull/1047
