### ISSUE TITLE
ohai ec2 plugin bug for server migrated from vmware environment into the AWS cloud

### ISSUE THREAD

**Issue by Stromweld** [chef/ohai#1050]
## Description

After migrating a windows 2012r2 and 2008r2 server from our local vmware environment to aws using the aws connector plugin for vmware chef-server failed to load the ec2 plugin and detect that the server is in AWS. To fix this I had to manually add an empty file c:\chef\ohai\hints\ec2.json.

After talking to @cheeseplus on slack he said this was a bug and I should open an issue here for it.

## Ohai Version

13.3.0

## Platform Version

Windows Server 2012r2 and Windows Server 2008r2

## Ohai Output

```
PS V:\> ohai.bat ec2
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.3.0/lib/ohai/system.rb:211:in `attributes_print': I cannot fin
d an attribute named ec2! (ArgumentError)
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.3.0/lib/ohai/application.rb:97:in `block in run_a
pplication'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.3.0/lib/ohai/application.rb:96:in `each'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.3.0/lib/ohai/application.rb:96:in `run_applicatio
n'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.3.0/lib/ohai/application.rb:78:in `run'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.3.0/bin/ohai:41:in `<top (required)>'
        from C:/opscode/chef/bin/ohai:28:in `load'
        from C:/opscode/chef/bin/ohai:28:in `<main>'
```

**Comment by Stromweld** [comment]
Here's the chef-client output error:
```
Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.
PS V:\> chef-client
Starting Chef Client, version 13.3.42
[2017-09-06T11:08:21-05:00] INFO: *** Chef 13.3.42 ***
[2017-09-06T11:08:21-05:00] INFO: Platform: x64-mingw32
[2017-09-06T11:08:21-05:00] INFO: Chef-client pid: 17328
[2017-09-06T11:08:26-05:00] INFO: Run List is [role[base-windows]]
[2017-09-06T11:08:26-05:00] INFO: Run List expands to [role-base-windows-nativex]
[2017-09-06T11:08:26-05:00] INFO: Starting Chef Run for PAW2AM-SOLAR01
[2017-09-06T11:08:26-05:00] INFO: Running start handlers
[2017-09-06T11:08:26-05:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["role-base-windows-nativex"]
[2017-09-06T11:08:26-05:00] INFO: Loading cookbooks [compat_resource@12.19.0, chef-sugar@3.4.0, seven_zip@2.0.2, network
ing-nativex@1.0.4, graphite-nativex@1.1.7, mingw@2.0.1, collectd_ii@1.1.0, ad-nativex@4.1.0, build-essential@8.0.3, cron
@4.1.3, logrotate@2.2.0, timezone_iii@1.0.4, yum-epel@2.1.2, aws@7.1.2, chef-client@8.1.8, ohai@5.2.0, windows@3.1.2, ho
stsfile@3.0.1, autopatch_ii@1.0.4, chef_client_updater@3.0.4, chocolatey@1.2.1, ms_dotnet@4.0.0, role-base-windows-nativ
ex@1.3.8, aws-tagging-nativex@2.0.1, solarwinds-nativex@1.5.4]
Synchronizing Cookbooks:
  - compat_resource (12.19.0)
  - chef-sugar (3.4.0)
  - seven_zip (2.0.2)
  - networking-nativex (1.0.4)
  - graphite-nativex (1.1.7)
  - mingw (2.0.1)
  - collectd_ii (1.1.0)
  - ad-nativex (4.1.0)
  - build-essential (8.0.3)
  - cron (4.1.3)
  - logrotate (2.2.0)
  - timezone_iii (1.0.4)
  - yum-epel (2.1.2)
  - aws (7.1.2)
  - chef-client (8.1.8)
  - ohai (5.2.0)
  - windows (3.1.2)
  - hostsfile (3.0.1)
  - autopatch_ii (1.0.4)
  - chef_client_updater (3.0.4)
  - chocolatey (1.2.1)
  - ms_dotnet (4.0.0)
  - role-base-windows-nativex (1.3.8)
  - aws-tagging-nativex (2.0.1)
  - solarwinds-nativex (1.5.4)
Installing Cookbook Gems:
[2017-09-06T11:08:31-05:00] INFO: Fetching gem metadata from https://www.rubygems.org/.............
Fetching version metadata from https://www.rubygems.org/..
Resolving dependencies...
Using aws-sigv4 1.0.2
Using jmespath 1.3.1
Using bundler 1.14.6
Using aws-sdk-core 2.10.39
Using aws-sdk-resources 2.10.39
Using aws-sdk 2.10.39
Bundle complete! 1 Gemfile dependency, 6 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Compiling Cookbooks...
================================================================================
Recipe Compile Error in c:/chef/cache/cookbooks/aws-tagging-nativex/attributes/default.rb
================================================================================
NoMethodError
-------------
undefined method `[]' for nil:NilClass
Cookbook Trace:
---------------
  c:/chef/cache/cookbooks/aws-tagging-nativex/attributes/default.rb:3:in `from_file'
Relevant File Content:
----------------------
c:/chef/cache/cookbooks/aws-tagging-nativex/attributes/default.rb:
  1:  default['aws-tag'] = [
  2:    {
  3>>     :awsid => node['ec2']['instance_id'],
  4:      :key => 'Enter desired Tag Key here.',
  5:      :value => 'Enter desired Tag Value here.'
  6:    }
  7:  ]
  8:
  9:  default['aws-tagging-nativex']['databag'] = ''
 10:  default['aws-tagging-nativex']['databag_entry'] = ''
 11:
System Info:
------------
chef_version=13.3.42
platform=windows
platform_version=6.3.9600
ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
program_name=C:/opscode/chef/bin/chef-client
executable=C:/opscode/chef/bin/chef-client
Running handlers:
[2017-09-06T11:08:31-05:00] ERROR: Running exception handlers
Running handlers complete
[2017-09-06T11:08:31-05:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 10 seconds
[2017-09-06T11:08:31-05:00] INFO: Sending resource update report (run-id: cf9fc4f8-7d2b-4be0-a9b5-fdf09a601c39)
[2017-09-06T11:08:31-05:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2017-09-06T11:08:31-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-09-06T11:08:31-05:00] FATAL: NoMethodError: undefined method `[]' for nil:NilClass
PS V:\>
```

**Comment by Stromweld** [comment]
and here is the stacktrace from the chef-client run:
```
Generated at 2017-09-06 11:08:31 -0500
NoMethodError: undefined method `[]' for nil:NilClass
c:/chef/cache/cookbooks/aws-tagging-nativex/attributes/default.rb:3:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/dsl/include_attribute.rb:39:in `block in include_attribute'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/dsl/include_attribute.rb:31:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/dsl/include_attribute.rb:31:in `include_attribute'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:213:in `load_attribute_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:202:in `load_attributes_from_cookbook'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:132:in `block in compile_attributes'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:131:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:131:in `compile_attributes'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:74:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/run_context.rb:192:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/client.rb:513:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/application/client.rb:457:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/application/client.rb:457:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:58:in `load'
C:/opscode/chef/bin/chef-client:58:in `<main>'
```

**Comment by tas50** [comment]
@Stromweld This is a tough one. We have a limited set of tools on Windows that help us to determine what kind of environment we're running on. We rely a lot on the manufacturer information that Amazon sets on the OS. If you can find anything else non-intrusive we could query on the OS side to determine that we're running in EC2 that would be really helpful. Otherwise you'll have to rely on the hint file.

**Comment by Stromweld** [comment]
I know it installed the EC2ConfigService, drivers, etc.... for windows automatically during the migration so there may be registry things that could be queried for to hint to ohai that this server is in AWS. You could also try a curl command to the ec2 meta-data and based on the output hint to ohai that it's an EC2 instance. http://169.254.169.254/latest/meta-data/.

I'm not sure if azure or google cloud or other services use meta-data and accessible the same way as AWS. If not then a return would indicate that it is in aws otherwise if they do, then you'd have to look for something unique in the return that tells it which cloud it's in. Like if http://169.254.169.254/latest/meta-data/ami-id returns an AMI ID then it's probably AWS.

**Comment by tas50** [comment]
Let me spin up a windows node in EC2 and see if I can expand upon our detection other than just querying out to the metadata service. We try to avoid that since it can cause issues in some environments that aren't ec2.

**Comment by tas50** [comment]
@Stromweld Do you have all the EC2 device drivers?

![screen shot 2017-09-06 at 1 19 55 pm](https://user-images.githubusercontent.com/1015200/30132845-af37f69a-9306-11e7-9495-87630d3dc634.png)

**Comment by Stromweld** [comment]
if the instance isn't a cloud machine then the url would return a non 200 http request code(which could be various error codes) and thus be known to not be in a cloud. Looks like AWS and Azure use the same base url to get instance meta-data, but have unique outputs. Google uses a very different url but still only accessible from within their cloud.

Here's links I found to docs on the major cloud providers meta-data services:
https://cloud.google.com/compute/docs/storing-retrieving-metadata
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
https://developers.digitalocean.com/documentation/metadata/
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service

**Comment by Stromweld** [comment]
I do have some, I expanded the ones with AWS in the name otherwise the other catagories didn't have drivers that indicated they'd be unique to AWS.

![screen shot 2017-09-06 at 3 26 21 pm](https://user-images.githubusercontent.com/3476391/30133095-25d11eec-9318-11e7-99e9-9f7515eaf56a.png)

**Comment by tas50** [comment]
Any chance you have the AWS network driver?

**Comment by Stromweld** [comment]
Not on the machine I migrated from vmware. It has the intel 82599 Virtual Function driver.

**Comment by Stromweld** [comment]
I did also find a few services that AWS must of installed as well.
Amazon SSM Agent
AWS Lite Guest Agent
Ec2Config

![screen shot 2017-09-06 at 3 31 33 pm](https://user-images.githubusercontent.com/3476391/30133295-fb4d9168-9318-11e7-8aa7-87beb7ff5028.png)

**Comment by Stromweld** [comment]
Looking at another native AWS windows instance I don't see the Amazon SSM Agent but I do see the AWS Lite Guest Agent and the Ec2Config services.

**Comment by tas50** [comment]
I have AWS Lite Guest Agent on a node I just spun up, but not the ec2config service. I'll see if I can add detection based on AWS Lite Guest Agent. That'll probably rope in a few more instances that we didn't catch before.

**Comment by tas50** [comment]
```ruby
  def has_aws_agent?
    # only run when we're on windows
    if RUBY_PLATFORM =~ /mswin|mingw32|windows/
      require "wmi-lite/wmi"
      wmi = WmiLite::Wmi.new
      if wmi.instances_of("Win32_Service").select { |x| %w{AWSLiteAgent Ec2Config}.include?(x["name"])}.empty?
        Ohai::Log.debug("Plugin EC2: has_aws_agent? == false (AWSLiteAgent or Ec2Config services not found)")
        false
      else
        Ohai::Log.debug("Plugin EC2: has_aws_agent? == true (AWSLiteAgent or Ec2Config services found)")
        false
      end
    else
      Ohai::Log.debug("Plugin EC2: has_aws_agent? == true (not on windows)")
      false
    end
  end
```

**Comment by Stromweld** [comment]
Just double checked and our Windows Server 2008r2 server that was migrated from vmware to aws also has those same services as well. It also has these drivers if your interested:

<img width="575" alt="screen shot 2017-09-06 at 4 29 59 pm" src="https://user-images.githubusercontent.com/3476391/30135618-36a91c5c-9321-11e7-9563-9636456f8ed9.png">

**Comment by tas50** [comment]
Also for anyone searching in the future here Amazon stopped using EC2Config with Windows 2016

**Comment by Stromweld** [comment]
found this in aws docs on how to identify if an instance is EC2 instance or not:
http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/identify_ec2_instances.html

**Comment by tas50** [comment]
This is fixed on master and will ship with the next Chef/Ohai. Thanks for the help tracking down the right approach @Stromweld
