### ISSUE TITLE
filesystem plugin timed out (df -P took over 30 seconds)

### ISSUE THREAD

**Issue by dkowis** [chef/ohai#1072]
## Description

Apparently `df -P` takes over 30 seconds to complete on my VM, I think because I have NFS mounts. Is there any way to exclude those NFS mounts? I'm interested in the mounted local filesystems, not the network mounted filesystems.

```
[2017-10-11T17:07:51-05:00] DEBUG: Plugin Filesystem: ran 'df -P' and timed out after 30 seconds
[2017-10-11T17:07:51-05:00] DEBUG: Plugin Filesystem threw #<Ohai::Exceptions::Exec: Command timed out after 30s:
Command exceeded allowed execution time, process terminated
---- Begin output of df -P ----
STDOUT:
STDERR:
---- End output of df -P ----
Ran df -P returned >
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/mixin/command.rb:46:in `rescue in shell_out'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/mixin/command.rb:37:in `shell_out'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/plugins/linux/filesystem.rb:53:in `block (2 levels) in <main>'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/dsl/plugin/versionvii.rb:88:in `instance_eval'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/dsl/plugin/versionvii.rb:88:in `run_plugin'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/dsl/plugin.rb:100:in `run'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/dsl/plugin.rb:184:in `safe_run'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/runner.rb:84:in `run_v7_plugin'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/runner.rb:43:in `run_plugin'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/system.rb:98:in `block in run_plugins'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/system.rb:97:in `each'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/system.rb:97:in `run_plugins'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/system.rb:75:in `all_plugins'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/application.rb:92:in `run_application'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/application.rb:78:in `run'
[2017-10-11T17:07:51-05:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/bin/ohai:41:in `<top (required)>'
[2017-10-11T17:07:51-05:00] DEBUG: /usr/bin/ohai:26:in `load'
[2017-10-11T17:07:51-05:00] DEBUG: /usr/bin/ohai:26:in `<main>'
```
## Ohai Version

8.23.0

## Platform Version

Ubuntu 16.04.3

**Comment by WheresAlice** [comment]
We're also seeing this on some of our servers.  It looks like it was introduced with #788 .  We are attempting to disable the filesystem plugin on affected servers, but also considering a change to Ohai to make the timeout time a configuration value.

**Comment by tas50** [comment]
Chef 14.4 will have a new config to allow extending this timeout thanks to @WheresAlice
