### ISSUE TITLE
Resolve Ruby 3 warnings in hostname plugin

### ISSUE THREAD

**Issue by tas50** [chef/ohai#1650]
```
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.33/lib/ohai/plugins/hostname.rb:180:in `gethostbyaddr': warning: Socket.gethostbyaddr is deprecated; use Addrinfo#getnameinfo instead. (StructuredWarnings::BuiltInWarning)
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.33/lib/ohai/plugins/hostname.rb:173:in `gethostbyname': warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead. (StructuredWarnings::BuiltInWarning)
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.33/lib/ohai/plugins/hostname.rb:180:in `gethostbyaddr': warning: Socket.gethostbyaddr is deprecated; use Addrinfo#getnameinfo instead. (StructuredWarnings::BuiltInWarning)
.
```

**Comment by jasonwbarnett** [comment]
I'm not sure if this is the same issue or I'm confused because of the warnings.

For context, I added Chef 17 to our integration testing pipeline and every version of Windows Server works except 2012R2. I continue to get this exception. I wish I had the full stack trace for you, but I haven't made the time to pull it, yet.

```
$$$$$$ chef-client.bat : C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:194:in `gethostbyname': warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead. (StructuredWarnings::BuiltInWarning)
    + CategoryInfo          : NotSpecified: (C:/opscode/chef...BuiltInWarning):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:201:in `gethostbyaddr': warning: Socket.gethostbyaddr is deprecated; use Addrinfo#getnameinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ <internal:C:/opscode/chef/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require': Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead (StructuredWarnings::StandardWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:194:in `gethostbyname': warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:201:in `gethostbyaddr': warning: Socket.gethostbyaddr is deprecated; use Addrinfo#getnameinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:194:in `gethostbyname': warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:201:in `gethostbyaddr': warning: Socket.gethostbyaddr is deprecated; use Addrinfo#getnameinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:194:in `gethostbyname': warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:201:in `gethostbyaddr': warning: Socket.gethostbyaddr is deprecated; use Addrinfo#getnameinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:194:in `gethostbyname': warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:201:in `gethostbyaddr': warning: Socket.gethostbyaddr is deprecated; use Addrinfo#getnameinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:194:in `gethostbyname': warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:201:in `gethostbyaddr': warning: Socket.gethostbyaddr is deprecated; use Addrinfo#getnameinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:194:in `gethostbyname': warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:201:in `gethostbyaddr': warning: Socket.gethostbyaddr is deprecated; use Addrinfo#getnameinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:194:in `gethostbyname': warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.0.42/lib/ohai/plugins/hostname.rb:201:in `gethostbyaddr': warning: Socket.gethostbyaddr is deprecated; use Addrinfo#getnameinfo instead. (StructuredWarnings::BuiltInWarning)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-windows-2012r2>.  Please see .kitchen/logs/default-windows-2012r2.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
+ exit 20
```

**Comment by tas50** [comment]
Is that using a chef package or the gems?

**Comment by jasonwbarnett** [comment]
> Is that using a chef package or the gems?

That's using a Gemfile

**Comment by Divya-001** [comment]
Do we have a fix/workaround for this?
Installed Chef Infra Client 17.2.29
And the embedded ruby within it shows 3.0.2p107
The hostname gem still has Socket.gethostbyname used in it. Warnings keep popping up

**Comment by tas50** [comment]
Fixed
