### ISSUE TITLE
cloud plugin fail on Oracle Cloud Infrastructure (OCI)

### ISSUE THREAD

**Issue by rnt** [chef/ohai#1779]
### Describe the Enhancement
**cloud plugin** need to detect if virtual machine is located in Oracle Cloud Infrastructure.

Right now we get, in Oracle Linux 8.5 with `chef-18.1.0-1.el8.x86_64` :

```[opc@core-oracle-85 ~]$ ohai cloud
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/ohai-18.0.26/lib/ohai/system.rb:185:in `attributes_print': I cannot find an attribute named cloud! (ArgumentError)
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/ohai-18.0.26/lib/ohai/application.rb:151:in `block in run_application'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/ohai-18.0.26/lib/ohai/application.rb:150:in `each'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/ohai-18.0.26/lib/ohai/application.rb:150:in `run_application'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/ohai-18.0.26/lib/ohai/application.rb:92:in `block in run'
	from /opt/chef/embedded/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/ohai-18.0.26/lib/ohai/application.rb:90:in `run'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/ohai-18.0.26/bin/ohai:25:in `<top (required)>'
	from /usr/bin/ohai:184:in `load'
	from /usr/bin/ohai:184:in `<main>'
```

### Describe the Need
We need to allow the **cloud plugin** to detect OCI and return at least the cloud provider.
All users using chef in OCI, must require this feature.

### Current Alternative
Right now we create a method in our cookbook, to check if we are located in OCI or not.

```ruby
  def in_oci?
    has_oci_chassis_asset_tag = false
    if file_exist?("/sys/devices/virtual/dmi/id/chassis_asset_tag")
      file_open("/sys/devices/virtual/dmi/id/chassis_asset_tag").each do |line|
        if /OracleCloud.com/.match?(line)
          has_oci_chassis_asset_tag = true
          break
        end
      end
    end
    has_oci_chassis_asset_tag
  end
```

### Can We Help You Implement This?
I only test this workarround in Oracle Linux in OCI, but not in all other OS flavours.

**Comment by rnt** [comment]
Closed with #1780
