### ISSUE TITLE
cloud_v2 fails to initialize on GCE hosts without external IP

### ISSUE THREAD

**Issue by jgoldschrafe** [chef/ohai#432]
On private hosts without an external IP address, ohai fails to initialize `cloud_v2` with:

    [2014-10-18T19:34:36+00:00] DEBUG: Plugin CloudV2 threw #<RuntimeError: ERROR: the ohai 'cloud' plugin failed with an IP address of '' : invalid address>

This appears to be caused by an empty `externalIp` in `gce['networkInterfaces']`:

    "networkInterfaces": [
       {
         "accessConfigs": [
           {
             "externalIp": "",
             "type": "ONE_TO_ONE_NAT"
           }
         ],
         "forwardedIps": [
    
         ],
         "ip": "10.129.60.194",
         "network": "projects/000000000000/networks/default"
       }
     ],

Full debug output:

    [2014-10-18T19:34:36+00:00] DEBUG: Parsing default via 10.129.0.1 dev eth0
    [2014-10-18T19:34:36+00:00] DEBUG: Parsing default via 10.129.0.1 dev eth0  metric 100
    [2014-10-18T19:34:36+00:00] DEBUG: Parsing 10.129.0.1 dev eth0  scope link
    [2014-10-18T19:34:36+00:00] DEBUG: default_interface set to eth0
    [2014-10-18T19:34:36+00:00] DEBUG: default_gateway set to 10.129.0.1
    [2014-10-18T19:34:36+00:00] DEBUG: Unable to determine default inet6 interface
    [2014-10-18T19:34:36+00:00] DEBUG: has_ec2_mac? == false
    [2014-10-18T19:34:36+00:00] DEBUG: looks_like_ec2? == false
    [2014-10-18T19:34:36+00:00] DEBUG: looks_like_gce? == true
    [2014-10-18T19:34:36+00:00] DEBUG: has_euca_mac? == false
    [2014-10-18T19:34:36+00:00] DEBUG: has_euca_mac? == false
    [2014-10-18T19:34:36+00:00] DEBUG: has_euca_mac? == false
    [2014-10-18T19:34:36+00:00] DEBUG: looks_like_euca? == false
    [2014-10-18T19:34:36+00:00] DEBUG: NOT ohai openstack
    [2014-10-18T19:34:36+00:00] DEBUG: No hints present for azure.
    [2014-10-18T19:34:36+00:00] DEBUG: Plugin CloudV2 threw #<RuntimeError: ERROR: the ohai 'cloud' plugin failed with an IP address of '' : invalid address>
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/plugins/cloud_v2.rb:109:in `rescue in validate_ip_addr'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/plugins/cloud_v2.rb:105:in `validate_ip_addr'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/plugins/cloud_v2.rb:54:in `add_ipv4_addr'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/plugins/cloud_v2.rb:135:in `block in get_gce_values'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/plugins/cloud_v2.rb:135:in `each'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/plugins/cloud_v2.rb:135:in `get_gce_values'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/plugins/cloud_v2.rb:278:in `block (2 levels) in <main>'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/dsl/plugin/versionvii.rb:90:in `instance_eval'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/dsl/plugin/versionvii.rb:90:in `run_plugin'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/dsl/plugin.rb:98:in `run'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/dsl/plugin.rb:169:in `safe_run'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/runner.rb:82:in `run_v7_plugin'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/runner.rb:43:in `run_plugin'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/system.rb:96:in `block in run_plugins'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/system.rb:95:in `each'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/system.rb:95:in `run_plugins'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/system.rb:73:in `all_plugins'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/application.rb:90:in `run_application'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/application.rb:70:in `run'
    [2014-10-18T19:34:36+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/bin/ohai:42:in `<top (required)>'
    [2014-10-18T19:34:36+00:00] DEBUG: /usr/bin/ohai:23:in `load'
    [2014-10-18T19:34:36+00:00] DEBUG: /usr/bin/ohai:23:in `<main>'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/system.rb:191:in `attributes_print': I cannot find an attribute named cloud_v2! (ArgumentError)
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/application.rb:94:in `block in run_application'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/application.rb:93:in `each'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/application.rb:93:in `run_application'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/application.rb:70:in `run'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/bin/ohai:42:in `<top (required)>'
        from /usr/bin/ohai:23:in `load'
        from /usr/bin/ohai:23:in `<main>'

**Comment by btm** [comment]
This went out in Ohai 8.1.0 today, but there were some unrelated bugs. Expect another release shortly.
