### ISSUE TITLE
ohai doesn't recognize cloud metadata in aws ap-southeast

### ISSUE THREAD

**Issue by runningman84** [chef/ohai#456]
I have two machines, one is located in Irland another in Australia.

The machine in Irland shows cloud metadata in ohai:
```
ubuntu@ip-10-96-26-245:~$ ec2metadata 
ami-id: ami-5a4bfb2d
ami-launch-index: 0
ami-manifest-path: ubuntu-eu-west-1/images/ubuntu-trusty-14.04-amd64-server-20141125.manifest.xml
ancestor-ami-ids: unavailable
availability-zone: eu-west-1b
block-device-mapping: ami
ephemeral0
root
instance-action: none
instance-id: i-59c710bd
instance-type: m3.medium
local-hostname: ip-10-96-26-245.eu-west-1.compute.internal
local-ipv4: 10.96.26.245
kernel-id: aki-52a34525
mac: unavailable
profile: default-paravirtual
product-codes: unavailable
public-hostname: ec2-54-75-120-151.eu-west-1.compute.amazonaws.com
public-ipv4: 54.75.120.151
public-keys: ['ssh-rsa xxx']
ramdisk-id: unavailable
reserveration-id: unavailable
security-groups: web-elb
user-data: unavailable

ubuntu@ip-10-96-26-245:~$ ohai cloud_v2
{
  "public_ipv4_addrs": [
    "54.75.120.151"
  ],
  "local_ipv4_addrs": [
    "10.96.26.245"
  ],
  "provider": "ec2",
  "public_hostname": "ec2-54-75-120-151.eu-west-1.compute.amazonaws.com",
  "local_hostname": "ip-10-96-26-245.eu-west-1.compute.internal",
  "public_ipv4": "54.75.120.151",
  "local_ipv4": "10.96.26.245"
}
```

The machine in Australia doesn't show any metadata in ohai:
```
ubuntu@ip-172-31-11-169:~$ ec2metadata 
ami-id: ami-970b62ad
ami-launch-index: 0
ami-manifest-path: (unknown)
ancestor-ami-ids: unavailable
availability-zone: ap-southeast-2b
block-device-mapping: ami
ephemeral0
root
instance-action: none
instance-id: i-1a8fced5
instance-type: t1.micro
local-hostname: ip-172-31-11-169.ap-southeast-2.compute.internal
local-ipv4: 172.31.11.169
kernel-id: aki-c362fff9
mac: unavailable
profile: default-paravirtual
product-codes: unavailable
public-hostname: ec2-54-66-147-213.ap-southeast-2.compute.amazonaws.com
public-ipv4: 54.66.147.213
public-keys: ['ssh-rsa xxx']
ramdisk-id: unavailable
reserveration-id: unavailable
security-groups: web-elb
user-data: unavailable

ubuntu@ip-172-31-11-169:~$ ohai  cloud_v2
/opt/chef/embedded/apps/ohai/lib/ohai/system.rb:189:in `attributes_print': I cannot find an attribute named cloud_v2! (ArgumentError)
	from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:94:in `block in run_application'
	from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:93:in `each'
	from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:93:in `run_application'
	from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:70:in `run'
	from /opt/chef/embedded/apps/ohai/bin/ohai:42:in `<top (required)>'
	from /usr/bin/ohai:23:in `load'
	from /usr/bin/ohai:23:in `<main>'
```

**Comment by runningman84** [comment]
The problem occurs if you start an instance in a vpc. Funny enough everything is working fine using ec2metadata tool.

**Comment by lamont-granquist** [comment]
Does using the hinting system for ohai fix this?  I seem to recall if you're using VPC that you have to use hints.

**Comment by lamont-granquist** [comment]
@btm isn't this problem with VPC nodes unable to determine if they're in EC2 which drove creating the hinting system in the first place?  This has nothing specific to do with ap-southeast, and there's really nothing to fix here?

**Comment by tas50** [comment]
This should get closed out.  EC2 detection is pretty basic and relies on a specific Xen like MAC address being seen.  I'm fairly confident that will not work with modern VPC AWS setups.  In order to reliably detect a node as being in EC2 you need the hint file to tip Ohai off that it should make a metadata call. It's not possible for Ohai to make metadata calls for every possible cloud provider with the hopes that one might return data.

**Comment by tas50** [comment]
Closing this out based on my previous comment.  As much as we'd like to magically detect clouds we rely on the hints to limit the time it takes to detect all attributes.
