### ISSUE TITLE
cannot encode to UTF-8 (FFI_Yajl::EncodeError)

### ISSUE THREAD

**Issue by theWeird** [chef/ohai#523]
I have the problem, that chef-client never writes back to the chef server. Instead it quits with a similar UTF-8 error message.

So I wanted to scan the output of ohai for invalid characters.

Instead I got another UTF-8 error message from ohai.

The chef-client machine is a debian wheezy system running as openVZ guest.

```
 # ohai
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:50:in `raise_error_for_status': Invalid UTF-8 string: cannot encode to UTF-8 (FFI_Yajl::EncodeError)
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `do_yajl_encode'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `encode'
	from /opt/chef/embedded/apps/ohai/lib/ohai/system.rb:181:in `json_pretty_print'
	from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:97:in `run_application'
	from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:70:in `run'
	from /opt/chef/embedded/apps/ohai/bin/ohai:42:in `<top (required)>'
	from /usr/bin/ohai:22:in `load'
	from /usr/bin/ohai:22:in `<main>'
```

Last lines of output from 'ohai -l debug':

```
[2015-04-14T10:22:59+02:00] DEBUG: has_ec2_mac? == false
[2015-04-14T10:22:59+02:00] DEBUG: looks_like_ec2? == false
[2015-04-14T10:22:59+02:00] DEBUG: Plugin GCE threw #<SocketError: getaddrinfo: Name or service not known>
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/mixin/gce_metadata.rb:30:in `pack_sockaddr_in'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/mixin/gce_metadata.rb:30:in `can_metadata_connect?'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/plugins/gce.rb:30:in `has_gce_metadata?'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/plugins/gce.rb:39:in `looks_like_gce?'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/plugins/gce.rb:43:in `block (2 levels) in <main>'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/dsl/plugin/versionvii.rb:90:in `instance_eval'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/dsl/plugin/versionvii.rb:90:in `run_plugin'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/dsl/plugin.rb:98:in `run'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/dsl/plugin.rb:169:in `safe_run'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/runner.rb:82:in `run_v7_plugin'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/runner.rb:43:in `run_plugin'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/system.rb:94:in `block in run_plugins'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/system.rb:93:in `each'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/system.rb:93:in `run_plugins'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/system.rb:71:in `all_plugins'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:90:in `run_application'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:70:in `run'
[2015-04-14T10:22:59+02:00] DEBUG: /opt/chef/embedded/apps/ohai/bin/ohai:42:in `<top (required)>'
[2015-04-14T10:22:59+02:00] DEBUG: /usr/bin/ohai:22:in `load'
[2015-04-14T10:22:59+02:00] DEBUG: /usr/bin/ohai:22:in `<main>'
[2015-04-14T10:22:59+02:00] DEBUG: has_euca_mac? == false
[2015-04-14T10:22:59+02:00] DEBUG: has_euca_mac? == false
[2015-04-14T10:22:59+02:00] DEBUG: has_euca_mac? == false
[2015-04-14T10:22:59+02:00] DEBUG: has_euca_mac? == false
[2015-04-14T10:22:59+02:00] DEBUG: has_euca_mac? == false
[2015-04-14T10:22:59+02:00] DEBUG: has_euca_mac? == false
[2015-04-14T10:22:59+02:00] DEBUG: looks_like_euca? == false
[2015-04-14T10:22:59+02:00] DEBUG: NOT ohai openstack
[2015-04-14T10:22:59+02:00] DEBUG: No hints present for azure.
[2015-04-14T10:22:59+02:00] DEBUG: ip_scopes: cannot load gem, plugin disabled: cannot load such file -- ipaddr_extensions
[2015-04-14T10:22:59+02:00] DEBUG: No data to collect for plugin SystemProfile. Continuing...
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:50:in `raise_error_for_status': Invalid UTF-8 string: cannot encode to UTF-8 (FFI_Yajl::EncodeError)
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `do_yajl_encode'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `encode'
	from /opt/chef/embedded/apps/ohai/lib/ohai/system.rb:181:in `json_pretty_print'
	from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:97:in `run_application'
	from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:70:in `run'
	from /opt/chef/embedded/apps/ohai/bin/ohai:42:in `<top (required)>'
	from /usr/bin/ohai:22:in `load'
	from /usr/bin/ohai:22:in `<main>'
```

**Comment by theWeird** [comment]
moved from https://github.com/chef/chef/issues/3216

**Comment by theWeird** [comment]
I installed chef on the host server and on another openVZ guest.
Host node works fine, the other guest machine has the same error.

**Comment by theWeird** [comment]
I ran ohai from command line on the host node and ran each plugin listed in the output on one of the openvz guests.
The problem is in plugin 'etc'
If I call `ohai etc` I get the known UTF8 error message.

**Comment by juliandunn** [comment]
Do you have any user accounts with weird encoding in their names or GECOS fields?

**Comment by apsoto** [comment]
Another data point, I notice that Chef 12.3 is install an ohai 8.3 even though I don't see a released 8.3 on rubygems (https://rubygems.org/gems/ohai)

**Comment by apsoto** [comment]
FYI re: the ohai 8.3 that was installed on a server by chef 12.3 that is showing this problem.  

I rolled it back to install chef 12.2.1 with a custom ohai 8.2 that includes the fix for #503 that isn't having this problem.  I'm not sure if a vanilla ohai 8.2 has this problem as I don't have anything available to test it on.

**Comment by juliandunn** [comment]
@apsoto I just asked @jdmundrawala to release 8.3.0 to Rubygems so at least we have that covered

**Comment by shalobalo** [comment]
I had the same problem in plugin 'NetworkListeners'
$ ohai |grep -A3 '"25": {'
        "25": {
          "address": "127.0.0.1",
          "pid": 0,
          "name": ""
$ ohai |grep -A3 '"25": {'
        "25": {
          "address": "127.0.0.1",
          "pid": 0,
          "name": "s\n    handle_line = /^Handle (0x[0-9A-F]{4}), DMI type (\\d+), (\\d+) bytes/\n    type_line = /^([A-Z][a-zA-Z ]+)( Information)?/\n  "

**Comment by lamont-granquist** [comment]
This should have been fixed in chef-client so that it'll clean up non-UTF8 strings to UTF8 and the node.save will always succeed.

**Comment by apsoto** [comment]
can you point to an issue or commit on chef-client ?
