### ISSUE TITLE
ohai, lsblk & charset

### ISSUE THREAD

**Issue by leshik** [chef/ohai#580]
Hi,
Given that linux chef node has USB stick mounted, and this stick is VFAT formatted and has volume label in national charset (cp866 in my case), ohai filesystem plugin fails as YAJL can't encode broken charset to JSON.
https://github.com/chef/ohai/blob/master/lib/ohai/plugins/linux/filesystem.rb#L128
This is due to the fact that lsblk outputs the label as is and doesn't convert it to current locale.
Surely, this is not chef or ohai fault, but.. Probably we should have some workaround here.

**Comment by mcquin** [comment]
It appears `FFI_Yajl` accepts a `validate_utf8 => false` option, which should resolve this issue. 

Can you provide a stacktrace?

**Comment by leshik** [comment]
Sure, but there is little useful information there:

$ cat /var/chef/cache/chef-stacktrace.out

```Generated at 2015-07-22 17:59:19 +0300
Chef::Exceptions::JSON::EncodeError: Unknown YAJL Error, please report this as a bug
/opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:107:in `rescue in to_json'
/opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:104:in `to_json'
/opt/chef/embedded/apps/chef/lib/chef/http/json_input.rb:35:in `handle_request'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:222:in `block in apply_request_middleware'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:220:in `each'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:220:in `inject'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:220:in `apply_request_middleware'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:141:in `request'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:118:in `put'
/opt/chef/embedded/apps/chef/lib/chef/node.rb:512:in `save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:257:in `save_updated_node'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:403:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:353:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:343:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:343:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:333:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:40:in `load'```

More recent chef complains: Invalid UTF-8 string '': cannot encode to UTF-8

**Comment by mcquin** [comment]
Thanks, I just wanted to make sure it was happening in the `#to_json` methods and not elsewhere.

**Comment by lamont-granquist** [comment]
I'm pretty certain I fixed this by adding validate_utf8: false:

https://github.com/chef/ohai/blob/ac9f5a2ae4ada9f2e6e821418ed3a9039bda9a91/lib/ohai/system.rb#L184-L186
