### ISSUE TITLE
IPv6 gateways ending in :: cause Ohai to not record any valid network interfaces (including IPv4).

### ISSUE THREAD

**Issue by williamsjj** [chef/ohai#791]
## Description

Having a default IPv6 gateway that ends in :: like `2604:1380:0:9900::` causes Ohai to throw an exception and not record **any** network information into `node[:network][:interfaces]` including IPv4.
## Ohai Version

8.11.1
## Platform Version

Ubuntu 14.04.3 x64
## Ohai Output

```
...
[2016-04-01T19:11:17+00:00] DEBUG: Plugin Groovy threw #<Errno::ENOENT: No such file or directory - groovy>
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:338:in `exec'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:338:in `block in fork_subprocess'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:316:in `fork'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:316:in `fork_subprocess'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:93:in `run_command'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:259:in `run_command'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/mixin/command.rb:33:in `shell_out'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/plugins/groovy.rb:29:in `block (2 levels) in <main>'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/dsl/plugin/versionvii.rb:90:in `instance_eval'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/dsl/plugin/versionvii.rb:90:in `run_plugin'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/dsl/plugin.rb:98:in `run'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/dsl/plugin.rb:169:in `safe_run'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/runner.rb:84:in `run_v7_plugin'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/runner.rb:43:in `run_plugin'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/system.rb:98:in `block in run_plugins'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/system.rb:97:in `each'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/system.rb:97:in `run_plugins'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/system.rb:75:in `all_plugins'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/application.rb:90:in `run_application'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/application.rb:78:in `run'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/bin/ohai:41:in `<top (required)>'
[2016-04-01T19:11:17+00:00] DEBUG: /usr/bin/ohai:22:in `load'
[2016-04-01T19:11:17+00:00] DEBUG: /usr/bin/ohai:22:in `<main>'
[2016-04-01T19:11:17+00:00] DEBUG: default route table is 'main'
[2016-04-01T19:11:17+00:00] DEBUG: Parsing default via 147.75.195.54 dev bond0
[2016-04-01T19:11:17+00:00] DEBUG: Parsing 10.0.0.0/8 via 10.100.77.128 dev bond0
[2016-04-01T19:11:17+00:00] DEBUG: Parsing 10.100.77.128/31 dev bond0  proto kernel  scope link  src 10.100.77.129
[2016-04-01T19:11:17+00:00] DEBUG: Skipping route entry whose src does not match the interface IP
[2016-04-01T19:11:17+00:00] DEBUG: Parsing 147.75.195.54/31 dev bond0  proto kernel  scope link  src 147.75.195.55
[2016-04-01T19:11:17+00:00] DEBUG: Parsing 192.168.10.0/24 dev tun0  proto kernel  scope link  src 192.168.10.1
[2016-04-01T19:11:17+00:00] DEBUG: default_interface set to bond0
[2016-04-01T19:11:17+00:00] DEBUG: default_gateway set to 147.75.195.54
[2016-04-01T19:11:17+00:00] DEBUG: Parsing 2604:1380:0:9900::/127 dev bond0  proto kernel  metric 256
[2016-04-01T19:11:17+00:00] DEBUG: Parsing fe80::/64 dev bond0  proto kernel  metric 256
[2016-04-01T19:11:17+00:00] DEBUG: Parsing default via 2604:1380:0:9900:: dev bond0  metric 1024
[2016-04-01T19:11:17+00:00] DEBUG: default_inet6_interface set to bond0
[2016-04-01T19:11:17+00:00] DEBUG: default_inet6_gateway set to 2604:1380:0:9900
[2016-04-01T19:11:17+00:00] DEBUG: Plugin Network threw #<ArgumentError: Invalid IP "2604:1380:0:9900">
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ipaddress-0.8.3/lib/ipaddress/ipv6.rb:101:in `initialize'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ipaddress-0.8.3/lib/ipaddress.rb:57:in `new'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ipaddress-0.8.3/lib/ipaddress.rb:57:in `parse'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ipaddress-0.8.3/lib/ipaddress.rb:211:in `IPAddress'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/plugins/linux/network.rb:359:in `route_is_valid_default_route?'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/plugins/linux/network.rb:386:in `block in favored_default_route'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/plugins/linux/network.rb:366:in `select'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/plugins/linux/network.rb:366:in `favored_default_route'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/plugins/linux/network.rb:482:in `block (3 levels) in <main>'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/plugins/linux/network.rb:454:in `each'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/plugins/linux/network.rb:454:in `block (2 levels) in <main>'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/dsl/plugin/versionvii.rb:88:in `instance_eval'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/dsl/plugin/versionvii.rb:88:in `run_plugin'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/dsl/plugin.rb:98:in `run'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/dsl/plugin.rb:169:in `safe_run'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/runner.rb:84:in `run_v7_plugin'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/runner.rb:43:in `run_plugin'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/system.rb:98:in `block in run_plugins'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/system.rb:97:in `each'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/system.rb:97:in `run_plugins'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/system.rb:75:in `all_plugins'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/application.rb:90:in `run_application'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/lib/ohai/application.rb:78:in `run'
[2016-04-01T19:11:17+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.11.1/bin/ohai:41:in `<top (required)>'
[2016-04-01T19:11:17+00:00] DEBUG: /usr/bin/ohai:22:in `load'
[2016-04-01T19:11:17+00:00] DEBUG: /usr/bin/ohai:22:in `<main>'
[2016-04-01T19:11:17+00:00] DEBUG: unexpected data line found before header; discarding:
Table at 0x7F4D3000.

[2016-04-01T19:11:17+00:00] DEBUG: unexpected data line found before header; discarding:
Port Connector Information

[2016-04-01T19:11:17+00:00] DEBUG: unexpected data line found before header; discarding:
    Internal Reference Designator: J1A1
...
```
## IP interfaces and routes:

```
# ip -f inet6 neigh show
fe80::561e:560c:907a:1bc0 dev bond0 lladdr 54:1e:56:79:49:c0 router STALE
2604:1380:0:9900:: dev bond0 lladdr 54:1e:56:79:49:c0 router STALE

# ip -o -f inet6 route show table main
2604:1380:0:9900::/127 dev bond0  proto kernel  metric 256
fe80::/64 dev bond0  proto kernel  metric 256
default via 2604:1380:0:9900:: dev bond0  metric 1024

# ip -d -s link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0
    RX: bytes  packets  errors  dropped overrun mcast
    33963606   134484   0       0       0       0
    TX: bytes  packets  errors  dropped carrier collsns
    33963606   134484   0       0       0       0
2: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether 0c:c4:7a:13:ae:02 brd ff:ff:ff:ff:ff:ff promiscuity 0
    RX: bytes  packets  errors  dropped overrun mcast
    473510999  1050124  0       0       0       5
    TX: bytes  packets  errors  dropped carrier collsns
    340587584  1613067  0       0       0       0
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc mq master bond0 state DOWN mode DEFAULT group default qlen 1000
    link/ether 0c:c4:7a:13:ae:03 brd ff:ff:ff:ff:ff:ff promiscuity 0
    RX: bytes  packets  errors  dropped overrun mcast
    0          0        0       0       0       0
    TX: bytes  packets  errors  dropped carrier collsns
    0          0        0       0       0       0
4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 0c:c4:7a:13:ae:02 brd ff:ff:ff:ff:ff:ff promiscuity 0
    bond
    RX: bytes  packets  errors  dropped overrun mcast
    473510999  1050124  0       0       0       5
    TX: bytes  packets  errors  dropped carrier collsns
    340587584  1613067  0       2       0       0
7: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 100
    link/none  promiscuity 0
    tun
    RX: bytes  packets  errors  dropped overrun mcast
    1393812    17132    0       0       0       0
    TX: bytes  packets  errors  dropped carrier collsns
    5130600    15936    0       0       0       0

# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP group default qlen 1000
    link/ether 0c:c4:7a:13:ae:02 brd ff:ff:ff:ff:ff:ff
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc mq master bond0 state DOWN group default qlen 1000
    link/ether 0c:c4:7a:13:ae:03 brd ff:ff:ff:ff:ff:ff
4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 0c:c4:7a:13:ae:02 brd ff:ff:ff:ff:ff:ff
    inet 147.75.195.55/31 brd 255.255.255.255 scope global bond0
       valid_lft forever preferred_lft forever
    inet 10.100.77.129/31 brd 255.255.255.255 scope global bond0:0
       valid_lft forever preferred_lft forever
    inet6 2604:1380:0:9900::1/127 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::ec4:7aff:fe13:ae02/64 scope link
       valid_lft forever preferred_lft forever
7: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none
    inet 192.168.10.1/24 brd 192.168.10.255 scope global tun0
       valid_lft forever preferred_lft forever
```

**Comment by crunchywelch** [comment]
+1 we support full v6, and I imagine this would be a common scenario, would love to see it fixed

**Comment by betawaffle** [comment]
This seems to be caused by a bad regex on https://github.com/chef/ohai/blob/eb75927881b10f1c60a26add31f6afe9f773330f/lib/ohai/plugins/linux/network.rb#L111

**Comment by q53** [comment]
Any changes?
After update chef client to 12.21.3-1.el7 half of my nodes became unmanaged.

**Comment by tas50** [comment]
@betawaffle Can you send me your route output by chance. I have the fix to the regex, but I need to get a test setup for your scenario.

**Comment by tas50** [comment]
This needs a test, but it should do ithttps://github.com/chef/ohai/pull/1058

**Comment by tas50** [comment]
This will go go out in the next release of chef/ohai. Thanks for the report
