### ISSUE TITLE
ohai dislikes inclusion

### ISSUE THREAD

**Issue by thenoid** [chef/ohai#809]
## Description

if the chef client.rb contains the chef::config.from_file (as rendered by the chef maintained chef-client cookbook) ohai, when run in standalone mode, throws an NameError: uninitialized constant Class::Chef

## Ohai Version
Ohai: 8.11.1
## Platform Version
RHEL
## Ohai Output

```
[root@default-vbox-ctp-rhel7x-x86-64 ~]# ohai -l debug -c /etc/chef/client.rb
[2016-04-22T15:14:56+00:00] WARN: Ohai::Config[:log_level] is set. Ohai::Config[:log_level] is deprecated and will be removed in future releases of ohai. Use ohai.log_level in your configuration file to configure :log_level for ohai.
[2016-04-22T15:14:56+00:00] WARN: Ohai::Config[:log_location] is set. Ohai::Config[:log_location] is deprecated and will be removed in future releases of ohai. Use ohai.log_location in your configuration file to configure :log_location for ohai.
FATAL: You have an error in your config file /etc/chef/client.rb

NameError: uninitialized constant Class::Chef
  /etc/chef/client.rb:21:in `block in from_string'
  /etc/chef/client.rb:20:in `each'
  /etc/chef/client.rb:20:in `from_string'
Relevant file content:
 20: Dir.glob(File.join("/etc/chef", "client.d", "*.rb")).each do |conf|
 21:   Chef::Config.from_file(conf)
 22: end
[2016-04-22T15:14:56+00:00] FATAL: You have an error in your config file /etc/chef/client.rb

NameError: uninitialized constant Class::Chef
  /etc/chef/client.rb:21:in `block in from_string'
  /etc/chef/client.rb:20:in `each'
  /etc/chef/client.rb:20:in `from_string'
Relevant file content:
 20: Dir.glob(File.join("/etc/chef", "client.d", "*.rb")).each do |conf|
 21:   Chef::Config.from_file(conf)
 22: end

```

**Comment by mcquin** [comment]
Hi @thenoid . We've release version 4.5.0 of the chef-client cookbook, which includes a fix for the issue you're seeing. Additionally you can edit your `/etc/chef/client.rb` to reference `ChefConfig::Config.from_file(file)` instead of `Chef::Config.from_file(file)` on line 21, there.
